### ISSUE TITLE
nginx not starting on boot

### ISSUE THREAD

**Issue by wardmundy** [djangopbx/djangopbx-install.sh#10]
Added _systemctl restart nginx_ to rc.local and set up rclocal.service to fix for the short term.

**Comment by AdrianFretwell** [comment]
Should be no need to do that!  If NGINX is not starting at boot, there is probably a valid reason:

I am aware there have been reports of nginx trying to start before the network layer is ready. This may be the issue in your case.
For systemd, this is resolved by adding a "wants" declaration to the nginx unit file, but I have checked and
/usr/lib/systemd/system/nginx.service looks OK on the installs that I have inspected.

If your unit file already has the "Wants" line, you could try further delaying the start of nginx by adding:
ExecStartPre=/bin/sleep 10
just below the PID declaration.

Let me know how it goes...

**Comment by wardmundy** [comment]
Inserting delay worked. Thanks.

ExecStartPre=/bin/sleep 10
just below the PID declaration.
