### ISSUE TITLE
Struggling in installation

### ISSUE THREAD

**Issue by neyamt** [djangopbx/djangopbx-install.sh#4]
I am trying to install and test DjangoPBX, All parts went well but i got some errors which needs to be shared to fix or guide me how to fix it:

Selecting previously unselected package uwsgi-plugin-python3.
(Reading database ... 63086 files and directories currently installed.)
Preparing to unpack .../uwsgi-plugin-python3_2.0.21-5.1_amd64.deb ...
Unpacking uwsgi-plugin-python3 (2.0.21-5.1) ...
Setting up uwsgi-plugin-python3 (2.0.21-5.1) ...
Processing triggers for man-db (2.11.2-2) ...
sed: can't read /home/django-pbx/pbx/pbx/settings.py: Not a directory
sed: can't read /home/django-pbx/pbx/pbx/settings.py: Not a directory
sed: can't read /home/django-pbx/pbx/pbx/scripts/resources/db/pgdb.py: Not a directory
sed: can't read /home/django-pbx/pbx/pbx/settings.py: Not a directory
sed: can't read /home/django-pbx/pbx/pbx/settings.py: Not a directory
sed: can't read /home/django-pbx/pbx/pbx/settings.py: Not a directory
sed: can't read /home/django-pbx/pbx/pbx/settings.py: Not a directory
sed: can't read /root/pbx-backup.sh: No such file or directory
sed: can't read /root/pbx-restore.sh: No such file or directory

Performing migrations...
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Loading user groups...
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

You are about to create a superuser to manage DjangoPBX, please use a strong, secure password.
Hint: Use the email format for the username e.g. <user@admin.mydomain.com>.
Press any key to continue

bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Default Access controls? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Default Email Templates? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Default Modules data? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Default SIP profiles? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Default Switch Variables? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Default Music on Hold data? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Number Translation data? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Conference Settings? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Default Settings? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Default Provision Settings? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Yealink Provision Settings? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Yealink vendor provision data? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Load Menu Defaults? y
bash: line 1: /home/django-pbx/envdpbx/bin/activate: No such file or directory

Set up crontab? y
/home/django-pbx/pbx/pbx/resources/home/django-pbx/crontab: Not a directory

Show database password? y
05e8757d48dedde9efcf

Show system password? y
a4b42e8c-4ed8-4b68-a151-b060f082c4f8
Created symlink /etc/systemd/system/multi-user.target.wants/freeswitch.service → /lib/systemd/system/freeswitch.service.
Job for uwsgi.service failed because the control process exited with error code.
See "systemctl status uwsgi.service" and "journalctl -xeu uwsgi.service" for details.

Installation Complete.

Make sure /etc/nftables.conf is correct for you!!
By default you must put your IP address in the white list to access ssh on port 22.

When you are sure that you will NOT LOCK YOURSELF OUT, issue the following command:
systemctl enable nftables

Then reboot!

Once you have rebooted, try logging in to your PBX at:
https://admin.mydomain.com

Thankyou for using DjangoPBX

root@PBXx:/usr/src/djangopbx-install#

**Comment by AdrianFretwell** [comment]
Difficult to say exactly what has gone wrong from the output.  But my guess would be that the django-pbx user was not created successfully and therefore the git clone failed, and pretty much everything else has failed as a consequence.

Clearly, some files and directories are missing.
Does /home/djangp-pbx exist?
Does /home/django-pbx/pbx exist?
If /home/django-pbx/pbx does exist, is there anything inside it?

Kind regards,
Adrian.

**Comment by neyamt** [comment]
yes it exists:

root@PBXx:/home/django-pbx# ls -lh
total 16K
drwxr-xr-x 5 django-pbx django-pbx 4.0K Jan 25 07:33 freeswitch
drwxr-xr-x 3 django-pbx django-pbx 4.0K Jan 25 06:57 media
-rw-r--r-- 1 root       root        344 Jan 25 07:34 pbx
drwxr-xr-x 2 django-pbx django-pbx 4.0K Jan 25 06:57 tmp

**Comment by AdrianFretwell** [comment]
Ok, I can see the problem, the pbx directory is owned by root.  I don not understand why because the install script runs the git command that creates that directory as django-pbx.  See below:

# clone the DjangoPBX application
sudo -u django-pbx bash -c 'cd /home/django-pbx && git clone https://github.com/djangopbx/djangopbx.git pbx'

**Comment by AdrianFretwell** [comment]
Thankyou for your feedback.  What I don't quite understand is the need to install sudo because the install script does this for you:

apt-get install -y sudo

**Comment by neyamt** [comment]
Yes, I just mentioned what I did differently than my first try, in which the installation succeeded. I hope this project gets better day by day.

@AdrianFretwell thank you for your help and support.
