### ISSUE TITLE
Debian 12 Install error - crontab not found

### ISSUE THREAD

**Issue by johnnyq** [djangopbx/djangopbx-install.sh#5]
Hello working on an initial install noticed the following error, This is from a Debian 12 Cloud KVM Image installed on top of Proxmox Hypervisor

![image](https://github.com/djangopbx/djangopbx-install.sh/assets/1812594/9f3f2860-9e02-41f6-bde2-bded67c9831f)

**Comment by AdrianFretwell** [comment]
Thank you for letting me know.  I assume in your environment the is no 'crontab' command available?
Below is what the installer tries to execute at that point:

sudo -u django-pbx bash -c 'crontab /home/django-pbx/pbx/pbx/resources/home/django-pbx/crontab'

**Comment by johnnyq** [comment]
yeah for some reason crontab is not installed by default for debian 12 at least their official KVM Cloud images
here https://cloud.debian.org/images/cloud/

If this is the case it may make sense to check for the crontab install and install before proceeding.
or possibly use the new systemd way of scheduling tasks which I think it set to replace cron entirely in the near future or if the future is now.

**Comment by AdrianFretwell** [comment]
The cron package is still available in Debian12, but I will keep an eye out for that changing.

In the meantime I will add and install for cron into the script

apt-get -y install cron

**Comment by johnnyq** [comment]
Awesome Thanks @AdrianFretwell
