### ISSUE TITLE
Feature: Remove all the unessesary install questions

### ISSUE THREAD

**Issue by johnnyq** [djangopbx/djangopbx-install.sh#6]
Great @AdrianFretwell Im recently found this project and am very excited for it development so I would like to report the Quality of Life improvements as I move through the install and config. 
for one I'm not sure why the installer is asking for a y input for all these defaults when it should just do it by default including the compiling the freeswitch modules etc, maybe make it a configurable option in the install.sh.
![image](https://github.com/djangopbx/djangopbx-install.sh/assets/1812594/2408eb4f-07a6-4b10-bf27-1cc0ce92d46f)

Thanks again

**Comment by AdrianFretwell** [comment]
Yes, I think we could add a "don't ask" configuration option.

**Comment by AdrianFretwell** [comment]
The feature you requested has been added:
https://github.com/djangopbx/djangopbx-install.sh/commit/7597f1b263239071d38bcd57ef8486047ba324ae

**Comment by johnnyq** [comment]
Fantastic Thanks @AdrianFretwell deff will make install a breeze
