### ISSUE TITLE
G729 does not install if selecting pkg install

### ISSUE THREAD

**Issue by chris021** [djangopbx/djangopbx-install.sh#7]
Hi,

I found that with a package install G729 does not get installed so i was able to run the install section from the script and this worked great after i added the libfreeswith-dev 

As an aside so far LOVE the concept. Slowly picking my way through the config to understand how it all hangs together. Really love what i see.

**Comment by chris021** [comment]
Hi, Sorry i was probably not clear. When I install using the package method "freeswitch_method=pkg" then no 729 codec is installed and Freewsitch produces log errors. I was able to follow the from sources method to compile just mod_bcg_729 to clear the errors and provide the 729 codec.  

Not a fault as such, just more of a FYI that this is the behavior experienced when using the PKG method.

**Comment by AdrianFretwell** [comment]
Hi Chris,
Yes I now understand.  I'm glad you got it sorted.  There is no package available for the royalty free bcg_729 codec so for the benefit of others reading this issue, here are the steps to download and compile it:

apt-get -y install libfreeswitch-dev git autoconf automake cmake libtool
cd /usr/src/
git clone https://github.com/xadhoom/mod_bcg729.git
cd mod_bcg729
make && make install

I have now also built this module and added it to the repo so it can be freely downloaded.

Thank you for bringing this to my attention.  I will mark the issue as closed.
