### ISSUE TITLE
NGINX Issues

### ISSUE THREAD

**Issue by wardmundy** [djangopbx/djangopbx-install.sh#8]
With Debian 12 installer, ability to rely on Debian packages is gone, NGINX doesn't start on reboot and when started manually yields a 400 error when accessed. Many of the options documented in the install.sh video no longer exist. Calling it alpha code is probably being charitable.

**Comment by AdrianFretwell** [comment]
Can you provide some more detail please, your environment, nginx logs and the output of:
"systemctl status nginx.service" 
and 
"journalctl -xeu nginx.service"

We have been testing the installer this afternoon on several different platforms and have not encountered this issue.  Please provide some more information.

Kind regards,
Adrian.

**Comment by wardmundy** [comment]
Sorry. My mistakes. Please close.
